'use strict';
const assert=require('assert');
const {getRequestIp,normalizeLocation,normalizeClientSource}=require('../lib/punch-metadata');
assert.strictEqual(getRequestIp({headers:{'cf-connecting-ip':'203.0.113.8'},socket:{remoteAddress:'172.18.0.2'}}),'203.0.113.8');
assert.strictEqual(getRequestIp({headers:{'x-forwarded-for':'198.51.100.4, 172.18.0.3'},socket:{remoteAddress:'172.18.0.2'}}),'198.51.100.4');
assert.strictEqual(getRequestIp({headers:{},socket:{remoteAddress:'::ffff:192.0.2.5'}}),'192.0.2.5');
assert.deepStrictEqual(normalizeLocation({location_status:'captured',latitude:33.77,longitude:-81.93,accuracy_meters:8.5}),{location_status:'captured',latitude:33.77,longitude:-81.93,accuracy_meters:8.5});
assert.deepStrictEqual(normalizeLocation({location_status:'captured',latitude:999,longitude:-81.93,accuracy_meters:8.5}),{location_status:'error',latitude:null,longitude:null,accuracy_meters:null});
assert.deepStrictEqual(normalizeLocation({location_status:'denied'}),{location_status:'denied',latitude:null,longitude:null,accuracy_meters:null});
assert.strictEqual(normalizeClientSource('mobile_pwa'),'mobile_pwa');
assert.strictEqual(normalizeClientSource('bad source!'),'web');
console.log('punch-metadata tests: PASS');
